// Generated by gencpp from file hrwros_msgs/SumaMultResponse.msg
// DO NOT EDIT!


#ifndef HRWROS_MSGS_MESSAGE_SUMAMULTRESPONSE_H
#define HRWROS_MSGS_MESSAGE_SUMAMULTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrwros_msgs
{
template <class ContainerAllocator>
struct SumaMultResponse_
{
  typedef SumaMultResponse_<ContainerAllocator> Type;

  SumaMultResponse_()
    : suma(0.0)
    , mult(0.0)  {
    }
  SumaMultResponse_(const ContainerAllocator& _alloc)
    : suma(0.0)
    , mult(0.0)  {
  (void)_alloc;
    }



   typedef double _suma_type;
  _suma_type suma;

   typedef double _mult_type;
  _mult_type mult;





  typedef boost::shared_ptr< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SumaMultResponse_

typedef ::hrwros_msgs::SumaMultResponse_<std::allocator<void> > SumaMultResponse;

typedef boost::shared_ptr< ::hrwros_msgs::SumaMultResponse > SumaMultResponsePtr;
typedef boost::shared_ptr< ::hrwros_msgs::SumaMultResponse const> SumaMultResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hrwros_msgs::SumaMultResponse_<ContainerAllocator1> & lhs, const ::hrwros_msgs::SumaMultResponse_<ContainerAllocator2> & rhs)
{
  return lhs.suma == rhs.suma &&
    lhs.mult == rhs.mult;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hrwros_msgs::SumaMultResponse_<ContainerAllocator1> & lhs, const ::hrwros_msgs::SumaMultResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hrwros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "875f0fb7e775efc0969a3d1a2fe732ae";
  }

  static const char* value(const ::hrwros_msgs::SumaMultResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x875f0fb7e775efc0ULL;
  static const uint64_t static_value2 = 0x969a3d1a2fe732aeULL;
};

template<class ContainerAllocator>
struct DataType< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrwros_msgs/SumaMultResponse";
  }

  static const char* value(const ::hrwros_msgs::SumaMultResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 suma	\n"
"float64 mult\n"
"\n"
"\n"
;
  }

  static const char* value(const ::hrwros_msgs::SumaMultResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.suma);
      stream.next(m.mult);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SumaMultResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrwros_msgs::SumaMultResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrwros_msgs::SumaMultResponse_<ContainerAllocator>& v)
  {
    s << indent << "suma: ";
    Printer<double>::stream(s, indent + "  ", v.suma);
    s << indent << "mult: ";
    Printer<double>::stream(s, indent + "  ", v.mult);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRWROS_MSGS_MESSAGE_SUMAMULTRESPONSE_H
