// Generated by gencpp from file hrwros_msgs/SumaMult.msg
// DO NOT EDIT!


#ifndef HRWROS_MSGS_MESSAGE_SUMAMULT_H
#define HRWROS_MSGS_MESSAGE_SUMAMULT_H

#include <ros/service_traits.h>


#include <hrwros_msgs/SumaMultRequest.h>
#include <hrwros_msgs/SumaMultResponse.h>


namespace hrwros_msgs
{

struct SumaMult
{

typedef SumaMultRequest Request;
typedef SumaMultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SumaMult
} // namespace hrwros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hrwros_msgs::SumaMult > {
  static const char* value()
  {
    return "e9e24fd947294769c45ffd94755c4345";
  }

  static const char* value(const ::hrwros_msgs::SumaMult&) { return value(); }
};

template<>
struct DataType< ::hrwros_msgs::SumaMult > {
  static const char* value()
  {
    return "hrwros_msgs/SumaMult";
  }

  static const char* value(const ::hrwros_msgs::SumaMult&) { return value(); }
};


// service_traits::MD5Sum< ::hrwros_msgs::SumaMultRequest> should match
// service_traits::MD5Sum< ::hrwros_msgs::SumaMult >
template<>
struct MD5Sum< ::hrwros_msgs::SumaMultRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hrwros_msgs::SumaMult >::value();
  }
  static const char* value(const ::hrwros_msgs::SumaMultRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrwros_msgs::SumaMultRequest> should match
// service_traits::DataType< ::hrwros_msgs::SumaMult >
template<>
struct DataType< ::hrwros_msgs::SumaMultRequest>
{
  static const char* value()
  {
    return DataType< ::hrwros_msgs::SumaMult >::value();
  }
  static const char* value(const ::hrwros_msgs::SumaMultRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hrwros_msgs::SumaMultResponse> should match
// service_traits::MD5Sum< ::hrwros_msgs::SumaMult >
template<>
struct MD5Sum< ::hrwros_msgs::SumaMultResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hrwros_msgs::SumaMult >::value();
  }
  static const char* value(const ::hrwros_msgs::SumaMultResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrwros_msgs::SumaMultResponse> should match
// service_traits::DataType< ::hrwros_msgs::SumaMult >
template<>
struct DataType< ::hrwros_msgs::SumaMultResponse>
{
  static const char* value()
  {
    return DataType< ::hrwros_msgs::SumaMult >::value();
  }
  static const char* value(const ::hrwros_msgs::SumaMultResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HRWROS_MSGS_MESSAGE_SUMAMULT_H
