// Generated by gencpp from file hrwros_msgs/SumaMultRequest.msg
// DO NOT EDIT!


#ifndef HRWROS_MSGS_MESSAGE_SUMAMULTREQUEST_H
#define HRWROS_MSGS_MESSAGE_SUMAMULTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrwros_msgs
{
template <class ContainerAllocator>
struct SumaMultRequest_
{
  typedef SumaMultRequest_<ContainerAllocator> Type;

  SumaMultRequest_()
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)  {
    }
  SumaMultRequest_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)  {
  (void)_alloc;
    }



   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;

   typedef double _c_type;
  _c_type c;

   typedef double _d_type;
  _d_type d;





  typedef boost::shared_ptr< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SumaMultRequest_

typedef ::hrwros_msgs::SumaMultRequest_<std::allocator<void> > SumaMultRequest;

typedef boost::shared_ptr< ::hrwros_msgs::SumaMultRequest > SumaMultRequestPtr;
typedef boost::shared_ptr< ::hrwros_msgs::SumaMultRequest const> SumaMultRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hrwros_msgs::SumaMultRequest_<ContainerAllocator1> & lhs, const ::hrwros_msgs::SumaMultRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c &&
    lhs.d == rhs.d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hrwros_msgs::SumaMultRequest_<ContainerAllocator1> & lhs, const ::hrwros_msgs::SumaMultRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hrwros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5c1b8d0c23e6e29f5d8d9fbdb957dac";
  }

  static const char* value(const ::hrwros_msgs::SumaMultRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5c1b8d0c23e6e29ULL;
  static const uint64_t static_value2 = 0xf5d8d9fbdb957dacULL;
};

template<class ContainerAllocator>
struct DataType< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrwros_msgs/SumaMultRequest";
  }

  static const char* value(const ::hrwros_msgs::SumaMultRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 a		\n"
"float64 b\n"
"float64 c\n"
"float64 d\n"
;
  }

  static const char* value(const ::hrwros_msgs::SumaMultRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SumaMultRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrwros_msgs::SumaMultRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrwros_msgs::SumaMultRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<double>::stream(s, indent + "  ", v.c);
    s << indent << "d: ";
    Printer<double>::stream(s, indent + "  ", v.d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRWROS_MSGS_MESSAGE_SUMAMULTREQUEST_H
